Name:           ros-lunar-rosbridge-server
Version:        0.8.4
Release:        0%{?dist}
Summary:        ROS rosbridge_server package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/rosbridge_server
Source0:        %{name}-%{version}.tar.gz

Requires:       python-twisted-core
Requires:       ros-lunar-rosapi
Requires:       ros-lunar-rosauth
Requires:       ros-lunar-rosbridge-library
Requires:       ros-lunar-rospy
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-rosapi
BuildRequires:  ros-lunar-rosbridge-library
BuildRequires:  ros-lunar-rospy

%description
A WebSocket interface to rosbridge.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Mon Oct 16 2017 Russell Toris <rctoris@wpi.edu> - 0.8.4-0
- Autogenerated by Bloom

* Mon Sep 11 2017 Russell Toris <rctoris@wpi.edu> - 0.8.3-0
- Autogenerated by Bloom

* Wed Aug 30 2017 Russell Toris <rctoris@wpi.edu> - 0.8.1-0
- Autogenerated by Bloom

